### ISSUE TITLE
Preview version will be installed

### ISSUE THREAD

**Issue by nowsprinting** [openupm/openupm-cli#395] opened 2024-09-12 20:32 UTC
The preview version will be installed when I don't specify a package version.
I want an option to exclude preview and experimental versions.

```
$ openupm --version
4.1.2

$ openupm add -f com.unity.test-framework
notice manifest modified com.unity.test-framework 1.1.14 => 2.0.1-pre.18
notice please open Unity project to apply changes
```

Stable com.unity.test-framework version is 1.4.5.
v2 is deprecated.

**Comment by favoyang** [comment] 2024-09-13 15:32
This is likely because Unity didn't use the npm dist-tag correctly. Typically, they should publish version 1.x with the "latest" tag and use the "next" tag for 2.0.1-pre. However, to be fair, openupm didn't follow this convention either. Our pipeline simply compares the version with the current latest version, and if the version is newer, it marks it with the "latest" tag or the "patch" tag.

In practice, the CLI could do more by introducing a virtual dist-tag "stable", so running `openupm add com.unity.test-framework@stable` would ignore all preview packages and select the latest stable version for you.

**Comment by ComradeVanti** [comment] 2024-09-13 17:34
Is this a duplicate of #64?

**Comment by favoyang** [comment] 2024-09-14 08:08
Yes. Though I propose different solutions, use '--stable' parameter or a special '@stable' tag.

**Comment by nowsprinting** [comment] 2024-09-14 09:44
Thank you for your reply.
I'd be happy if the virtual dist-tag "stable" were introduced!

**Comment by ComradeVanti** [comment] 2024-09-29 11:19
Just implemented the `@stable` tag and tested it with the provided example by @nowsprinting. Seems to work but I'll leave it open a bit for feedback.

**Comment by ComradeVanti** [comment] 2024-09-29 11:28
A pull request for this feature is now open at #404. @nowsprinting if you have the time you could take a look to see if it also works for you. Thanks :)

**Comment by nowsprinting** [comment] 2024-09-29 11:54
@ComradeVanti san,
Thanks!!!
I built the code in the PR, and it works as expected!

```
$ openupm add com.unity.test-framework@stable
notice modified com.unity.test-framework 1.4.4 => 1.4.5
```

**Comment by ComradeVanti** [comment] 2024-10-01 06:43
@nowsprinting great to know. The PR is now merged 🚀

**Closed by ComradeVanti** 2024-10-01 06:43 UTC

**Comment by nowsprinting** [comment] 2024-10-01 12:41
Thanks!!!
