### ISSUE TITLE
Error: Cannot find module 'node-fetch'

### ISSUE THREAD

**Issue by SCastanedaMunoz** [openupm/openupm-cli#371] opened 2024-07-08 23:05 UTC
Hey,

I am looking into openupm as an alternative package distribution for Unity. I am getting the following error when running the openupm-cli on a Mac (Apple-Sillicon).

```
node:internal/modules/cjs/loader:1222
  throw err;
  ^

Error: Cannot find module 'node-fetch'
Require stack:
- /usr/local/lib/node_modules/openupm-cli/lib/io/check-url.js
- /usr/local/lib/node_modules/openupm-cli/lib/cli/index.js
- /usr/local/lib/node_modules/openupm-cli/lib/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
    at Module._load (node:internal/modules/cjs/loader:1045:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Module.require (node:internal/modules/cjs/loader:1304:12)
    at require (node:internal/modules/helpers:123:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/openupm-cli/lib/io/check-url.js:7:38)
    at Module._compile (node:internal/modules/cjs/loader:1467:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1551:10)
    at Module.load (node:internal/modules/cjs/loader:1282:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/openupm-cli/lib/io/check-url.js',
    '/usr/local/lib/node_modules/openupm-cli/lib/cli/index.js',
    '/usr/local/lib/node_modules/openupm-cli/lib/index.js'
  ]
}

Node.js v22.4.1
```

I have tried to use openupm-cli with different versions of node:

* v18.20.4
* v20.15.1
* v22.4.1 

All to the same result. Any ideas?

I will download the source code and try to take a look myself when I have some time.

**Comment by favoyang** [comment] 2024-07-09 06:40
@SCastanedaMunoz Thanks for reporting the issue.

Please roll back to v3.1.0, while we debug the issue.

```
npm install openupm-cli@3.1.0 -g
```

**Comment by favoyang** [comment] 2024-07-09 07:20
Hi @ComradeVanti,

The direct import for `node-fetch` is introduced in v3.2.0 [src/io/check-url.ts](https://github.com/openupm/openupm-cli/compare/3.1.0...3.2.0#diff-a635b553790c0572d3c4826208c40c0af8866d302045099de64671002f4a4833), but missing an entry in package.json.

The test is passed because `node-fetch` is an indirect dev dependency.

**Comment by ComradeVanti** [comment] 2024-07-09 07:25
Just reproduced the problem on Windows 11 with Node 20.

> The direct import for node-fetch is introduced in v3.2.0 src/io/check-url.ts, but missing an entry in package.json.

That seems likely. I'll take a look

**Comment by ComradeVanti** [comment] 2024-07-09 07:44
Should be fixed in 3.3.1. @SCastanedaMunoz if the issue persists.

**Closed** 2024-07-09 07:43 UTC
Labels: bug

**Comment by SCastanedaMunoz** [comment] 2024-07-10 19:40
I can confirm that the fix seems to be working when using Node.js 22. When using Node.js 18 or Node.js 20 the following errors occurs:

This error seems to be specific to my M2 MacBook when using Node.Js 18 or 20. On my Windows machine, it works with any of the 3 versions.

```
/Users/santiago.munoz/.nvm/versions/node/v18.20.3/lib/node_modules/openupm-cli/lib/io/check-url.js:7
const node_fetch_1 = __importDefault(require("node-fetch"));
                                     ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/santiago.munoz/.nvm/versions/node/v18.20.3/lib/node_modules/node-fetch/src/index.js from /Users/santiago.munoz/.nvm/versions/node/v18.20.3/lib/node_modules/openupm-cli/lib/io/check-url.js not supported.
Instead change the require of index.js in /Users/santiago.munoz/.nvm/versions/node/v18.20.3/lib/node_modules/openupm-cli/lib/io/check-url.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/santiago.munoz/.nvm/versions/node/v18.20.3/lib/node_modules/openupm-cli/lib/io/check-url.js:7:38)
    at Object.<anonymous> (/Users/santiago.munoz/.nvm/versions/node/v18.20.3/lib/node_modules/openupm-cli/lib/cli/index.js:43:21)
    at Object.<anonymous> (/Users/santiago.munoz/.nvm/versions/node/v18.20.3/lib/node_modules/openupm-cli/lib/index.js:4:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.20.3
```

```
node:internal/modules/cjs/loader:1143
  throw err;
  ^

Error: Cannot find module 'node-fetch'
Require stack:
- /usr/local/lib/node_modules/openupm-cli/lib/io/check-url.js
- /usr/local/lib/node_modules/openupm-cli/lib/cli/index.js
- /usr/local/lib/node_modules/openupm-cli/lib/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/openupm-cli/lib/io/check-url.js:7:38)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/openupm-cli/lib/io/check-url.js',
    '/usr/local/lib/node_modules/openupm-cli/lib/cli/index.js',
    '/usr/local/lib/node_modules/openupm-cli/lib/index.js'
  ]
}

Node.js v18.20.4
```

**Comment by ComradeVanti** [comment] 2024-07-12 09:58
Alright I see. Not sure what the issue is here. If you find out more information and there is something on our end we can do, please open a new issue.
